package com.tm.enums;

public enum InsightType {
    SCIENCE_ENGINE_ACTIVE,
    ENERGY_BOTTLENECK,
    MC_SHORTAGE,
    OPPONENT_NEAR_MAYOR,
    OPPONENT_NEAR_GARDENER,
    OPPONENT_NEAR_BUILDER,
    SELF_NEAR_MILESTONE,
    TEMPERATURE_STALLED
}
