package com.tm.enums;

public enum InsightType {
    SCIENCE_ENGINE_ACTIVE,
    ENERGY_BOTTLENECK,
    MC_SHORTAGE,

    OPPONENT_NEAR_MAYOR,
    OPPONENT_NEAR_GARDENER,
    OPPONENT_NEAR_BUILDER,

    SELF_NEAR_TERRAFORMER,
    SELF_NEAR_MAYOR,
    SELF_NEAR_BUILDER,
    SELF_NEAR_GARDENER,
    SELF_NEAR_PLANNER,

    TEMPERATURE_STALLED,

    SCORE_LAGGING
}
